import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Lang = "ar" | "en" | "fr";

const translations = {
  en: {
    appName: "TERMCHAT",
    channels: "Channels",
    directMessages: "Direct Messages",
    users: "Users",
    online: "online",
    offline: "Offline",
    newChannel: "+ new",
    exit: "exit",
    settings: "Settings",
    noChannels: "No channels yet",
    noOtherUsers: "No other users yet",
    noMessages: "No messages yet",
    sendFirst: "Send the first message!",
    noResults: "No messages found",
    messagePlaceholder: "Message...",
    replyPlaceholder: "Reply to",
    captionPlaceholder: "Add caption...",
    typing: "typing",
    people: "people",
    today: "Today",
    yesterday: "Yesterday",
    members: "members",
    online2: "Online",
    selectRoom: "Select a channel or conversation from the sidebar to start messaging",
    endToEnd: "End-to-end · Real-time · Firebase",
    account: "Account",
    preferences: "Preferences",
    language: "Language",
    sounds: "Sounds",
    soundOn: "On",
    soundOff: "Off",
    editProfile: "Edit Profile",
    saveProfile: "Save",
    cancel: "Cancel",
    saving: "Saving...",
    displayName: "Display Name",
    bio: "About",
    email: "Email",
    memberSince: "Member since",
    close: "Close",
    uploadPhoto: "Change Photo",
    chooseLanguage: "Interface Language",
    arabic: "العربية",
    english: "English",
    french: "Français",
    profileUpdated: "Profile updated!",
    bioPlaceholder: "Write something about yourself...",
    namePlaceholder: "Your display name",
    sendMessage: "Send Message",
    deleteRoom: "Delete",
    deleteRoomConfirm: "All messages will be permanently deleted. This cannot be undone.",
    deleteRoomTitle: "Delete",
    cancelDelete: "Cancel",
    deleting: "Deleting...",
    search: "Search messages...",
    searchResults: "result",
    searchResultsPlural: "results",
    justNow: "Just now",
    minsAgo: "m ago",
    hoursAgo: "h ago",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    newChannelTitle: "New Channel",
    signOut: "Sign out",
    noChannelsYet: "No channels yet",
    createChannelDesc: "Create a channel to start a group conversation",
    createChannel: "Create channel",
    noDirectMessages: "No direct messages yet",
    goToPeople: "Go to the People tab to start a conversation",
    unknown: "Unknown",
    startConversation: "Start a conversation",
    lastSeen: "Last seen",
    total: "total",
    channelNameLabel: "Channel Name",
    addMembers: "Add Members",
    optional: "optional",
    selectedCount: "selected",
    creating: "Creating...",
    createChannelBtn: "Create Channel",
    channelRequired: "Channel name is required",
    channelTooShort: "Name must be at least 2 characters",
    failedCreateChannel: "Failed to create channel. Try again.",
    failedUploadPhoto: "Failed to upload photo. Try again.",
    noBioOwn: "No bio yet. Tap edit to add one.",
    noBio: "No bio.",
    searchPlaceholder: "Search...",
    noMessages2: "No messages yet",
    channelNamePlaceholder: "channel-name",
    editMsg: "Edit",
    deleteMsg: "Delete message",
    pinMsg: "Pin message",
    unpinMsg: "Unpin",
    pinnedMsg: "Pinned message",
    replyMsg: "Reply",
    edited: "edited",
    confirmDeleteMsg: "Delete this message?",
    membersTitle: "Members",
    adminLabel: "Admin",
    youLabel: "You",
    kickMember: "Remove",
    confirmKick: "Remove this member from the channel?",
    editChannel: "Edit channel",
    channelDescription: "Description",
    descPlaceholder: "What's this channel about?",
    archiveChannel: "Archive",
    unarchiveChannel: "Unarchive",
    archivedChannels: "Archived",
    showArchived: "Show archived",
    hideArchived: "Hide archived",
    globalSearch: "Search everywhere",
    globalSearchPlaceholder: "Search channels and conversations...",
    noSearchResults: "No results found",
    myStatus: "My Status",
    setStatus: "Set a status",
    statusPlaceholder: "e.g. 🔥 Working on something...",
    clearStatus: "Clear status",
    reactions: "React",
    imageReady: "Image ready · add a caption below",
    linkPreview: "Link preview",
    description: "Description",
  },
  ar: {
    appName: "تيرم‌شات",
    channels: "القنوات",
    directMessages: "الرسائل المباشرة",
    users: "المستخدمون",
    online: "متصل",
    offline: "غير متصل",
    newChannel: "+ جديد",
    exit: "خروج",
    settings: "الإعدادات",
    noChannels: "لا توجد قنوات بعد",
    noOtherUsers: "لا يوجد مستخدمون آخرون",
    noMessages: "لا توجد رسائل بعد",
    sendFirst: "أرسل أول رسالة!",
    noResults: "لا توجد نتائج",
    messagePlaceholder: "رسالة...",
    replyPlaceholder: "رد على",
    captionPlaceholder: "أضف تعليقاً...",
    typing: "يكتب",
    people: "أشخاص",
    today: "اليوم",
    yesterday: "أمس",
    members: "أعضاء",
    online2: "متصل",
    selectRoom: "اختر قناة أو محادثة من الشريط الجانبي للبدء",
    endToEnd: "تشفير كامل · فوري · Firebase",
    account: "الحساب",
    preferences: "التفضيلات",
    language: "اللغة",
    sounds: "الأصوات",
    soundOn: "مفعّل",
    soundOff: "معطّل",
    editProfile: "تعديل الملف",
    saveProfile: "حفظ",
    cancel: "إلغاء",
    saving: "جاري الحفظ...",
    displayName: "الاسم",
    bio: "نبذة عني",
    email: "البريد الإلكتروني",
    memberSince: "عضو منذ",
    close: "إغلاق",
    uploadPhoto: "تغيير الصورة",
    chooseLanguage: "لغة الواجهة",
    arabic: "العربية",
    english: "English",
    french: "Français",
    profileUpdated: "تم تحديث الملف الشخصي!",
    bioPlaceholder: "اكتب شيئاً عن نفسك...",
    namePlaceholder: "اسمك المعروض",
    sendMessage: "إرسال رسالة",
    deleteRoom: "حذف",
    deleteRoomConfirm: "ستُحذف جميع الرسائل بشكل دائم ولا يمكن التراجع.",
    deleteRoomTitle: "حذف",
    cancelDelete: "إلغاء",
    deleting: "جاري الحذف...",
    search: "ابحث في الرسائل...",
    searchResults: "نتيجة",
    searchResultsPlural: "نتائج",
    justNow: "الآن",
    minsAgo: "د",
    hoursAgo: "س",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    newChannelTitle: "قناة جديدة",
    signOut: "تسجيل الخروج",
    noChannelsYet: "لا توجد قنوات بعد",
    createChannelDesc: "أنشئ قناة لبدء محادثة جماعية",
    createChannel: "إنشاء قناة",
    noDirectMessages: "لا توجد رسائل مباشرة بعد",
    goToPeople: "اذهب إلى تبويب الأشخاص لبدء محادثة",
    unknown: "غير معروف",
    startConversation: "ابدأ محادثة",
    lastSeen: "آخر ظهور",
    total: "المجموع",
    channelNameLabel: "اسم القناة",
    addMembers: "إضافة أعضاء",
    optional: "اختياري",
    selectedCount: "محدد",
    creating: "جاري الإنشاء...",
    createChannelBtn: "إنشاء قناة",
    channelRequired: "اسم القناة مطلوب",
    channelTooShort: "يجب أن يكون الاسم حرفين على الأقل",
    failedCreateChannel: "فشل إنشاء القناة. حاول مرة أخرى.",
    failedUploadPhoto: "فشل رفع الصورة. حاول مرة أخرى.",
    noBioOwn: "لا توجد نبذة بعد. اضغط تعديل لإضافة واحدة.",
    noBio: "لا توجد نبذة.",
    searchPlaceholder: "بحث...",
    noMessages2: "لا توجد رسائل بعد",
    channelNamePlaceholder: "اسم-القناة",
    editMsg: "تعديل",
    deleteMsg: "حذف الرسالة",
    pinMsg: "تثبيت الرسالة",
    unpinMsg: "إلغاء التثبيت",
    pinnedMsg: "رسالة مثبتة",
    replyMsg: "رد",
    edited: "معدّل",
    confirmDeleteMsg: "هل تريد حذف هذه الرسالة؟",
    membersTitle: "الأعضاء",
    adminLabel: "مشرف",
    youLabel: "أنت",
    kickMember: "إزالة",
    confirmKick: "هل تريد إزالة هذا العضو من القناة؟",
    editChannel: "تعديل القناة",
    channelDescription: "الوصف",
    descPlaceholder: "ما موضوع هذه القناة؟",
    archiveChannel: "أرشفة",
    unarchiveChannel: "إلغاء الأرشفة",
    archivedChannels: "المؤرشفة",
    showArchived: "عرض المؤرشفة",
    hideArchived: "إخفاء المؤرشفة",
    globalSearch: "بحث شامل",
    globalSearchPlaceholder: "ابحث في القنوات والمحادثات...",
    noSearchResults: "لا توجد نتائج",
    myStatus: "حالتي",
    setStatus: "تعيين حالة",
    statusPlaceholder: "مثال: 🔥 أعمل على شيء...",
    clearStatus: "مسح الحالة",
    reactions: "تفاعل",
    imageReady: "الصورة جاهزة · أضف تعليقاً",
    linkPreview: "معاينة الرابط",
    description: "الوصف",
  },
  fr: {
    appName: "TERMCHAT",
    channels: "Canaux",
    directMessages: "Messages directs",
    users: "Utilisateurs",
    online: "en ligne",
    offline: "Hors ligne",
    newChannel: "+ nouveau",
    exit: "quitter",
    settings: "Paramètres",
    noChannels: "Aucun canal pour l'instant",
    noOtherUsers: "Aucun autre utilisateur",
    noMessages: "Aucun message pour l'instant",
    sendFirst: "Envoyez le premier message !",
    noResults: "Aucun message trouvé",
    messagePlaceholder: "Message...",
    replyPlaceholder: "Répondre à",
    captionPlaceholder: "Ajouter une légende...",
    typing: "écrit",
    people: "personnes",
    today: "Aujourd'hui",
    yesterday: "Hier",
    members: "membres",
    online2: "En ligne",
    selectRoom: "Sélectionnez un canal ou une conversation dans la barre latérale",
    endToEnd: "Bout en bout · Temps réel · Firebase",
    account: "Compte",
    preferences: "Préférences",
    language: "Langue",
    sounds: "Sons",
    soundOn: "Activé",
    soundOff: "Désactivé",
    editProfile: "Modifier le profil",
    saveProfile: "Enregistrer",
    cancel: "Annuler",
    saving: "Enregistrement...",
    displayName: "Nom affiché",
    bio: "À propos",
    email: "E-mail",
    memberSince: "Membre depuis",
    close: "Fermer",
    uploadPhoto: "Changer la photo",
    chooseLanguage: "Langue de l'interface",
    arabic: "العربية",
    english: "English",
    french: "Français",
    profileUpdated: "Profil mis à jour !",
    bioPlaceholder: "Écrivez quelque chose sur vous...",
    namePlaceholder: "Votre nom affiché",
    sendMessage: "Envoyer un message",
    deleteRoom: "Supprimer",
    deleteRoomConfirm: "Tous les messages seront définitivement supprimés. Cette action est irréversible.",
    deleteRoomTitle: "Supprimer",
    cancelDelete: "Annuler",
    deleting: "Suppression...",
    search: "Rechercher des messages...",
    searchResults: "résultat",
    searchResultsPlural: "résultats",
    justNow: "À l'instant",
    minsAgo: "min",
    hoursAgo: "h",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    newChannelTitle: "Nouveau canal",
    signOut: "Se déconnecter",
    noChannelsYet: "Aucun canal pour l'instant",
    createChannelDesc: "Créez un canal pour démarrer une conversation de groupe",
    createChannel: "Créer un canal",
    noDirectMessages: "Aucun message direct pour l'instant",
    goToPeople: "Allez dans l'onglet Personnes pour démarrer une conversation",
    unknown: "Inconnu",
    startConversation: "Démarrer une conversation",
    lastSeen: "Vu(e) dernièrement",
    total: "total",
    channelNameLabel: "Nom du canal",
    addMembers: "Ajouter des membres",
    optional: "optionnel",
    selectedCount: "sélectionné(s)",
    creating: "Création...",
    createChannelBtn: "Créer le canal",
    channelRequired: "Le nom du canal est requis",
    channelTooShort: "Le nom doit comporter au moins 2 caractères",
    failedCreateChannel: "Échec de la création du canal. Réessayez.",
    failedUploadPhoto: "Échec du téléchargement de la photo. Réessayez.",
    noBioOwn: "Pas encore de bio. Appuyez sur Modifier pour en ajouter une.",
    noBio: "Pas de bio.",
    searchPlaceholder: "Rechercher...",
    noMessages2: "Aucun message pour l'instant",
    channelNamePlaceholder: "nom-du-canal",
    editMsg: "Modifier",
    deleteMsg: "Supprimer le message",
    pinMsg: "Épingler",
    unpinMsg: "Désépingler",
    pinnedMsg: "Message épinglé",
    replyMsg: "Répondre",
    edited: "modifié",
    confirmDeleteMsg: "Supprimer ce message ?",
    membersTitle: "Membres",
    adminLabel: "Admin",
    youLabel: "Vous",
    kickMember: "Retirer",
    confirmKick: "Retirer ce membre du canal ?",
    editChannel: "Modifier le canal",
    channelDescription: "Description",
    descPlaceholder: "De quoi parle ce canal ?",
    archiveChannel: "Archiver",
    unarchiveChannel: "Désarchiver",
    archivedChannels: "Archivés",
    showArchived: "Afficher les archivés",
    hideArchived: "Masquer les archivés",
    globalSearch: "Recherche globale",
    globalSearchPlaceholder: "Rechercher dans les canaux...",
    noSearchResults: "Aucun résultat trouvé",
    myStatus: "Mon statut",
    setStatus: "Définir un statut",
    statusPlaceholder: "Ex: 🔥 En train de travailler...",
    clearStatus: "Effacer le statut",
    reactions: "Réagir",
    imageReady: "Image prête · ajoutez une légende",
    linkPreview: "Aperçu du lien",
    description: "Description",
  },
};

export type T = typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: T;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem("tc-lang") as Lang) ?? "ar";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("tc-lang", l);
  };

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang], isRTL: lang === "ar" }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used within LanguageProvider");
  return ctx;
}
